# -*- coding: utf-8 -*-
"""ocr_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qdnsiYHFtXg-WmuRLz1GqAjNj0RsU3-j
"""

# SUPER SIMPLE OCR DEMO
print("=" * 50)
print("Limi AI Report Extractor")
print("=" * 50)

# Simulated report data (pretend we extracted this)
reports = [
    {"module": "L-701", "signal": "98%", "location": "Zone A", "status": "Optimal"},
    {"module": "L-702", "signal": "75%", "location": "Zone B", "status": "Needs Maintenance"},
    {"module": "L-703", "signal": "45%", "location": "Zone C", "status": "Critical"}
]

print("\n📊 EXTRACTED DATA:")
print("-" * 30)
for report in reports:
    print(f"Module: {report['module']}")
    print(f"Signal: {report['signal']}")
    print(f"Location: {report['location']}")
    print(f"Status: {report['status']}")
    print("-" * 30)

print("\n✅ AI Processing Complete!")